return {
    patterns = {
        {pattern = "attempt to index nil", hint = "Nil value accessed", tip = "Initialize variable before use"},
        {pattern = "attempt to index a nil", hint = "Nil value indexed", tip = "Check if variable exists before indexing"},
        {pattern = "attempt to call nil", hint = "Nil called as function", tip = "Define function before calling"},
        {pattern = "attempt to call a nil", hint = "Missing function", tip = "Function may not be loaded or returned"},
        {pattern = "attempt to index global", hint = "Global is nil", tip = "Declare global variable first"},
        {pattern = "index a nil value", hint = "Nil index access", tip = "Use and/or operator to guard against nil"},
        {pattern = "'end' expected", hint = "Missing 'end'", tip = "Close all blocks with 'end'"},
        {pattern = "expected 'end'", hint = "'end' keyword missing", tip = "Count your if/for/while/function blocks"},
        {pattern = "<eof>", hint = "Unexpected end of file", tip = "Check missing 'end', ')', ']', or '}'"},
        {pattern = "unexpected symbol", hint = "Invalid syntax", tip = "Check code near error line for typos"},
        {pattern = "unexpected symbol near", hint = "Syntax error near symbol", tip = "Review syntax at reported position"},
        {pattern = "unexpected symbol near '='", hint = "Invalid assignment", tip = "Check if you meant '==' for comparison"},
        {pattern = "unexpected symbol near 'local'", hint = "Local misplaced", tip = "Local can only be at top level or block start"},
        {pattern = "unexpected symbol near 'function'", hint = "Function syntax error", tip = "Check function declaration syntax"},
        {pattern = "unexpected symbol near 'if'", hint = "If statement error", tip = "Ensure if has then and end"},
        {pattern = "unexpected symbol near 'then'", hint = "Then misplaced", tip = "Then must follow condition"},
        {pattern = "unexpected symbol near 'else'", hint = "Else without if", tip = "Else must be inside if block"},
        {pattern = "unexpected symbol near 'elseif'", hint = "Elseif without if", tip = "Elseif must follow if or elseif"},
        {pattern = "unexpected symbol near 'for'", hint = "For loop syntax", tip = "Use 'for i=1,10 do' format"},
        {pattern = "unexpected symbol near 'while'", hint = "While loop syntax", tip = "Use 'while condition do' format"},
        {pattern = "unexpected symbol near 'repeat'", hint = "Repeat loop syntax", tip = "Use 'repeat ... until condition'"},
        {pattern = "unexpected symbol near 'until'", hint = "Until without repeat", tip = "Until must close a repeat block"},
        {pattern = "unexpected symbol near 'goto'", hint = "Goto syntax error", tip = "Use 'goto label' with matching '::label::'"},
        {pattern = "unexpected symbol near 'break'", hint = "Break outside loop", tip = "Break can only be used in loops"},
        {pattern = "unexpected symbol near 'return'", hint = "Return misplaced", tip = "Return must be last in block"},
        {pattern = "unexpected symbol near 'nil'", hint = "Nil used incorrectly", tip = "Nil is a value, not an operator"},
        {pattern = "unexpected symbol near 'true'", hint = "True used incorrectly", tip = "True is boolean, check syntax"},
        {pattern = "unexpected symbol near 'false'", hint = "False used incorrectly", tip = "False is boolean, check syntax"},
        {pattern = "unexpected symbol near '...'", hint = "Vararg misplaced", tip = "... can only be used in functions"},
        {pattern = "unexpected symbol near '::'", hint = "Label syntax error", tip = "Use '::label::' for labels"},
        {pattern = "unexpected symbol near '}'", hint = "Brace mismatch", tip = "Check opening braces"},
        {pattern = "unexpected symbol near ']'", hint = "Bracket mismatch", tip = "Check opening brackets"},
        {pattern = "unexpected symbol near ')'", hint = "Parenthesis mismatch", tip = "Check opening parentheses"},
        {pattern = "attempt to perform arithmetic", hint = "Math on non-number", tip = "Use tonumber() for conversion"},
        {pattern = "attempt to perform arithmetic on", hint = "Arithmetic error", tip = "Ensure all operands are numbers"},
        {pattern = "attempt to add", hint = "Addition error", tip = "Both operands must be numbers"},
        {pattern = "attempt to subtract", hint = "Subtraction error", tip = "Both operands must be numbers"},
        {pattern = "attempt to multiply", hint = "Multiplication error", tip = "Both operands must be numbers"},
        {pattern = "attempt to divide", hint = "Division error", tip = "Both operands must be numbers"},
        {pattern = "attempt to modulus", hint = "Modulo error", tip = "Both operands must be numbers"},
        {pattern = "attempt to exponentiate", hint = "Power error", tip = "Both operands must be numbers"},
        {pattern = "attempt to negate", hint = "Negation error", tip = "Operand must be a number"},
        {pattern = "division by zero", hint = "Divide by zero", tip = "Check denominator is not zero"},
        {pattern = "attempt to concatenate", hint = "Concat on non-string", tip = "Use tostring() before concatenation"},
        {pattern = "attempt to concatenate a", hint = "Invalid concat operand", tip = "Convert non-strings with tostring()"},
        {pattern = "attempt to get length", hint = "# on invalid type", tip = "Use # only on strings and tables"},
        {pattern = "attempt to get length of", hint = "Length operator error", tip = "Strings and tables only"},
        {pattern = "attempt to compare", hint = "Compare incompatible types", tip = "Ensure same type comparison"},
        {pattern = "attempt to compare two", hint = "Type mismatch in comparison", tip = "Compare numbers with numbers, strings with strings"},
        {pattern = "attempt to compare number with", hint = "Number vs non-number", tip = "Convert other type to number first"},
        {pattern = "attempt to compare string with", hint = "String vs non-string", tip = "Convert other type to string first"},
        {pattern = "bad argument", hint = "Wrong argument type", tip = "Check function parameters"},
        {pattern = "bad argument #", hint = "Invalid argument", tip = "Refer to function documentation"},
        {pattern = "bad argument #1", hint = "First argument invalid", tip = "Check first parameter type"},
        {pattern = "bad argument #2", hint = "Second argument invalid", tip = "Check second parameter type"},
        {pattern = "bad argument #3", hint = "Third argument invalid", tip = "Check third parameter type"},
        {pattern = "bad argument #4", hint = "Fourth argument invalid", tip = "Check fourth parameter type"},
        {pattern = "bad argument #5", hint = "Fifth argument invalid", tip = "Check fifth parameter type"},
        {pattern = "too many arguments", hint = "Excess arguments passed", tip = "Reduce number of arguments"},
        {pattern = "too few arguments", hint = "Missing arguments", tip = "Provide all required parameters"},
        {pattern = "no value", hint = "Function returned nothing", tip = "Add return statement to function"},
        {pattern = "return not correct", hint = "Invalid return value", tip = "Check expected return type"},
        {pattern = "multiple returns", hint = "Too many returns", tip = "Limit return values"},
        {pattern = "table index is nil", hint = "Nil table key", tip = "Ensure key exists before use"},
        {pattern = "invalid key", hint = "Invalid table key type", tip = "Use string or number keys only"},
        {pattern = "invalid value", hint = "Invalid table value", tip = "Check inserted value type"},
        {pattern = "table has no value", hint = "Missing table field", tip = "Check if field exists before access"},
        {pattern = "table overflow", hint = "Table too large", tip = "Reduce table size or use multiple tables"},
        {pattern = "unfinished string", hint = "Unclosed string", tip = "Close string with matching quotes"},
        {pattern = "unfinished long string", hint = "Unclosed long string", tip = "Close with same brackets as opened"},
        {pattern = "invalid escape", hint = "Invalid escape character", tip = "Use double backslash \\\\ or valid escape"},
        {pattern = "invalid escape sequence", hint = "Bad escape code", tip = "Valid escapes: \\a \\b \\f \\n \\r \\t \\v \\' \\\" \\\\"},
        {pattern = "unmatched delimiter", hint = "String delimiter mismatch", tip = "Match quotes or brackets"},
        {pattern = "global", hint = "Undefined global variable", tip = "Declare variable with local or assign value"},
        {pattern = "attempt to index global", hint = "Nil global accessed", tip = "Check spelling and scope"},
        {pattern = "global variable", hint = "Undeclared variable", tip = "Use local for local variables"},
        {pattern = "name conflicts", hint = "Duplicate variable name", tip = "Rename conflicting variables"},
        {pattern = "shadowing", hint = "Variable hidden by local", tip = "Use different variable names"},
        {pattern = "is not a valid member", hint = "Property not found", tip = "Check instance property name"},
        {pattern = "is not a valid member of", hint = "Invalid property", tip = "Property doesn't exist on this instance"},
        {pattern = "cannot assign property", hint = "Read-only property", tip = "Property cannot be changed"},
        {pattern = "property is read-only", hint = "Read-only access", tip = "This property cannot be modified"},
        {pattern = "invalid property", hint = "Property doesn't exist", tip = "Check documentation for correct property"},
        {pattern = "Parent must be a valid Instance", hint = "Nil parent", tip = "Create parent instance before assigning"},
        {pattern = "cannot set parent", hint = "Parent assignment failed", tip = "Check if parent is valid"},
        {pattern = "Parent is locked", hint = "Parent locked", tip = "Property cannot be reparented"},
        {pattern = "Class mismatch", hint = "Wrong instance type", tip = "Expected specific instance class"},
        {pattern = "attempt to yield", hint = "Yield not allowed", tip = "Avoid wait() in callbacks and metamethods"},
        {pattern = "attempt to yield across", hint = "Yield boundary error", tip = "Cannot yield in protected context"},
        {pattern = "cannot resume", hint = "Coroutine resume error", tip = "Check coroutine status before resuming"},
        {pattern = "cannot resume dead coroutine", hint = "Dead coroutine", tip = "Create new coroutine instead"},
        {pattern = "cannot resume running coroutine", hint = "Coroutine already running", tip = "Cannot resume active coroutine"},
        {pattern = "cannot resume normal", hint = "Invalid resume", tip = "Check if coroutine is suspended"},
        {pattern = "cannot yield", hint = "Yield not permitted", tip = "Current context doesn't allow yielding"},
        {pattern = "stack overflow", hint = "Infinite recursion", tip = "Add base case to recursive function"},
        {pattern = "stack underflow", hint = "Stack empty", tip = "Internal Lua error"},
        {pattern = "too many results", hint = "Too many return values", tip = "Limit return values"},
        {pattern = "recursion depth exceeded", hint = "Deep recursion", tip = "Convert to iterative solution"},
        {pattern = "JSON encode failed", hint = "Invalid JSON data", tip = "Check for non-serializable values"},
        {pattern = "JSON decode failed", hint = "Invalid JSON string", tip = "Check JSON format is valid"},
        {pattern = "invalid JSON", hint = "Malformed JSON", tip = "Use JSON validator online"},
        {pattern = "JSON expected object", hint = "Not a JSON object", tip = "JSON must start with { or ["},
        {pattern = "invalid hex", hint = "Bad hex color", tip = "Use format RRGGBB or #RRGGBB"},
        {pattern = "invalid hex color", hint = "Color parsing failed", tip = "Hex must be 6 characters (0-9,A-F)"},
        {pattern = "Invalid RGB values", hint = "RGB out of range", tip = "Use values 0-255"},
        {pattern = "Color3 expected", hint = "Not a Color3", tip = "Pass Color3.new(r,g,b)"},
        {pattern = "ColorSequence invalid", hint = "Bad ColorSequence", tip = "Use valid ColorSequenceKeypoint array"},
        {pattern = "Invalid UDim2", hint = "Malformed UDim2", tip = "Use UDim2.new(scale, offset)"},
        {pattern = "Invalid UDim", hint = "Malformed UDim", tip = "Use UDim.new(scale, offset)"},
        {pattern = "invalid scale", hint = "Scale must be number", tip = "Scale is a number"},
        {pattern = "invalid offset", hint = "Offset must be number", tip = "Offset is a number"},
        {pattern = "expected number, got", hint = "Number required", tip = "Use tonumber() for conversion"},
        {pattern = "expected string, got", hint = "String required", tip = "Use tostring() for conversion"},
        {pattern = "expected table, got", hint = "Table required", tip = "Ensure value is a table"},
        {pattern = "expected boolean, got", hint = "Boolean required", tip = "Use 'not not value' to convert"},
        {pattern = "expected function, got", hint = "Function required", tip = "Pass function reference, not call result"},
        {pattern = "expected thread, got", hint = "Thread required", tip = "Use coroutine.create()"},
        {pattern = "expected userdata, got", hint = "Instance required", tip = "Ensure value is Roblox instance"},
        {pattern = "expected nil, got", hint = "Nil expected", tip = "Value should be nil"},
        {pattern = "expected lightuserdata", hint = "Lightuserdata expected", tip = "Internal Lua type"},
        {pattern = "not a valid Enum", hint = "Invalid Enum", tip = "Check Enum spelling and existence"},
        {pattern = "is not a valid member of Enum", hint = "Bad Enum member", tip = "Check Roblox docs for correct name"},
        {pattern = "Enum item not found", hint = "Missing Enum value", tip = "Enum may not exist in this version"},
        {pattern = "cannot convert to Enum", hint = "Enum conversion failed", tip = "Value not convertible to Enum"},
        {pattern = "Request failed", hint = "HTTP request failed", tip = "Check URL and internet connection"},
        {pattern = "Http request failed", hint = "HTTP error", tip = "Check URL, method, and headers"},
        {pattern = "cannot request", hint = "HTTP not allowed", tip = "Enable HTTP requests in game settings"},
        {pattern = "HTTP 404", hint = "Not found", tip = "URL may be invalid or moved"},
        {pattern = "HTTP 403", hint = "Forbidden", tip = "Access denied to resource"},
        {pattern = "HTTP 500", hint = "Server error", tip = "Server side issue, try again later"},
        {pattern = "connection refused", hint = "Server unreachable", tip = "Check if server is online"},
        {pattern = "timeout", hint = "Request timeout", tip = "Server too slow, increase timeout or retry"},
        {pattern = "invalid URL", hint = "Malformed URL", tip = "Check URL format (include http:// or https://)"},
        {pattern = "cannot open file", hint = "File access failed", tip = "Check file path and permissions"},
        {pattern = "cannot write file", hint = "Write failed", tip = "Ensure folder exists and has space"},
        {pattern = "cannot read file", hint = "Read failed", tip = "File may not exist or is corrupt"},
        {pattern = "file not found", hint = "Missing file", tip = "Check file name and path"},
        {pattern = "permission denied", hint = "No permission", tip = "Cannot access file in this context"},
        {pattern = "is a directory", hint = "Path is directory", tip = "Expected file, got folder"},
        {pattern = "no such file", hint = "File doesn't exist", tip = "Create file before reading"},
        {pattern = "disk full", hint = "Storage full", tip = "Free up space on device"},
        {pattern = "invalid Goal", hint = "Invalid tween goal", tip = "Check property names and value types"},
        {pattern = "invalid TweenInfo", hint = "Bad TweenInfo", tip = "Check TweenInfo parameters"},
        {pattern = "cannot tween", hint = "Tween failed", tip = "Property may not be tweens"},
        {pattern = "tween interrupted", hint = "Tween stopped", tip = "Another tween may have replaced it"},
        {pattern = "is not a valid service", hint = "Service not found", tip = "Verify service name case sensitivity"},
        {pattern = "GetService failed", hint = "Service unavailable", tip = "Service may not exist in this context"},
        {pattern = "service unavailable", hint = "Service not ready", tip = "Wait for service to load"},
        {pattern = "not enough memory", hint = "Out of memory", tip = "Clean up unused objects and tables"},
        {pattern = "memory allocation failed", hint = "Memory error", tip = "Reduce memory usage"},
        {pattern = "out of memory", hint = "Memory exhausted", tip = "Use collectgarbage() or optimize code"},
        {pattern = "Argument 1 missing", hint = "First arg missing", tip = "Provide required parameter"},
        {pattern = "Argument 2 missing", hint = "Second arg missing", tip = "Provide required parameter"},
        {pattern = "Argument 3 missing", hint = "Third arg missing", tip = "Provide required parameter"},
        {pattern = "Argument 4 missing", hint = "Fourth arg missing", tip = "Provide required parameter"},
        {pattern = "Argument 5 missing", hint = "Fifth arg missing", tip = "Provide required parameter"},
        {pattern = "argument missing or nil", hint = "Nil argument", tip = "Argument cannot be nil"},
        {pattern = "Invalid argument to FindFirstChild", hint = "Invalid child name", tip = "Pass string to FindFirstChild"},
        {pattern = "Invalid argument to WaitForChild", hint = "Invalid child name", tip = "Pass valid string name"},
        {pattern = "FindFirstChild requires string", hint = "Wrong type", tip = "Child name must be string"},
        {pattern = "WaitForChild timeout", hint = "Child never appeared", tip = "Increase timeout or check if child exists"},
        {pattern = "Clone failed", hint = "Cannot clone", tip = "Instance may not be clonable"},
        {pattern = "Destroy called on nil", hint = "Already destroyed", tip = "Check if instance exists before destroy"},
        {pattern = "cannot spawn", hint = "Spawn failed", tip = "Reduce concurrent threads"},
        {pattern = "spawn error", hint = "Thread error", tip = "Check spawned function for errors"},
        {pattern = "delay error", hint = "Delay function error", tip = "Check delayed function"},
        {pattern = "task.spawn failed", hint = "Task spawn error", tip = "Function may have errored"},
        {pattern = "coroutine dead", hint = "Dead coroutine", tip = "Cannot resume dead coroutine"},
        {pattern = "coroutine running", hint = "Already running", tip = "Cannot resume running coroutine"},
        {pattern = "coroutine suspended", hint = "Not suspended", tip = "Coroutine not in suspended state"},
        {pattern = "cannot create coroutine", hint = "Create failed", tip = "Function may be invalid"},
        {pattern = "string expected", hint = "Not a string", tip = "Convert to string first"},
        {pattern = "pattern too complex", hint = "Complex pattern", tip = "Simplify Lua pattern"},
        {pattern = "invalid pattern capture", hint = "Bad capture", tip = "Check pattern parentheses"},
        {pattern = "gsub error", hint = "Replace failed", tip = "Check pattern and replacement"},
        {pattern = "format error", hint = "Format failed", tip = "Check format specifiers"},
        {pattern = "string length overflow", hint = "String too long", tip = "String exceeds memory limit"},
        {pattern = "math domain error", hint = "Invalid math input", tip = "Check sqrt of negative, log of zero, etc"},
        {pattern = "math overflow", hint = "Value too large", tip = "Result exceeds Lua number range"},
        {pattern = "table expected", hint = "Not a table", tip = "Operand must be table"},
        {pattern = "sort comparator error", hint = "Bad sort function", tip = "Comparator must return boolean"},
        {pattern = "table sort failed", hint = "Sort error", tip = "Check comparator consistency"},
        {pattern = "pack error", hint = "Pack failed", tip = "Table pack error"},
        {pattern = "unpack error", hint = "Unpack failed", tip = "Check table and indices"},
        {pattern = "invalid __index", hint = "Bad __index", tip = "__index must be table or function"},
        {pattern = "invalid __newindex", hint = "Bad __newindex", tip = "__newindex must be table or function"},
        {pattern = "invalid __call", hint = "Bad __call", tip = "__call must be function"},
        {pattern = "invalid __add", hint = "Bad __add", tip = "__add must be function"},
        {pattern = "invalid __sub", hint = "Bad __sub", tip = "__sub must be function"},
        {pattern = "invalid __mul", hint = "Bad __mul", tip = "__mul must be function"},
        {pattern = "invalid __div", hint = "Bad __div", tip = "__div must be function"},
        {pattern = "invalid __mod", hint = "Bad __mod", tip = "__mod must be function"},
        {pattern = "invalid __pow", hint = "Bad __pow", tip = "__pow must be function"},
        {pattern = "invalid __unm", hint = "Bad __unm", tip = "__unm must be function"},
        {pattern = "invalid __concat", hint = "Bad __concat", tip = "__concat must be function"},
        {pattern = "invalid __len", hint = "Bad __len", tip = "__len must be function"},
        {pattern = "invalid __eq", hint = "Bad __eq", tip = "__eq must be function"},
        {pattern = "invalid __lt", hint = "Bad __lt", tip = "__lt must be function"},
        {pattern = "invalid __le", hint = "Bad __le", tip = "__le must be function"},
        {pattern = "invalid __tostring", hint = "Bad __tostring", tip = "__tostring must be function"},
        {pattern = "invalid __metatable", hint = "Bad __metatable", tip = "__metatable protected"},
        {pattern = "debug not allowed", hint = "Debug disabled", tip = "Debug functions may be blocked"},
        {pattern = "invalid level", hint = "Bad debug level", tip = "Level must be valid number"},
        {pattern = "module not found", hint = "Missing module", tip = "Check module name and path"},
        {pattern = "loadstring failed", hint = "Compile error", tip = "Check loaded code syntax"},
        {pattern = "loadfile failed", hint = "File load error", tip = "File may not exist or has syntax error"},
        {pattern = "require failed", hint = "Require error", tip = "Module may have error or not found"},
        {pattern = "circular require", hint = "Circular dependency", tip = "Module requires itself directly or indirectly"},
        {pattern = "Workspace is not a valid member", hint = "Invalid Workspace", tip = "Use game.Workspace"},
        {pattern = "Players is not a valid member", hint = "Invalid Players", tip = "Use game.Players"},
        {pattern = "Lighting is not a valid member", hint = "Invalid Lighting", tip = "Use game.Lighting"},
        {pattern = "ReplicatedStorage is not valid", hint = "Invalid ReplicatedStorage", tip = "Use game.ReplicatedStorage"},
        {pattern = "ServerStorage not accessible", hint = "Server storage", tip = "May not be accessible from client"},
        {pattern = "cannot access from client", hint = "Server only", tip = "This feature only works on server"},
        {pattern = "cannot access from server", hint = "Client only", tip = "This feature only works on client"},
        {pattern = "remote event failed", hint = "Remote error", tip = "Check remote arguments"},
        {pattern = "remote function failed", hint = "Remote call error", tip = "Function may have errored"},
        {pattern = "too many remote arguments", hint = "Arg limit exceeded", tip = "Reduce remote arguments"},
        {pattern = "remote not found", hint = "Missing remote", tip = "Remote instance may not exist"},
        {pattern = "DataStore error", hint = "DataStore failed", tip = "Check key and scope"},
        {pattern = "key too long", hint = "Key exceeded limit", tip = "DataStore keys max 50 chars"},
        {pattern = "value too large", hint = "Value exceeded limit", tip = "DataStore values max 4MB"},
        {pattern = "too many requests", hint = "Rate limited", tip = "Slow down DataStore requests"},
        {pattern = "data store not ready", hint = "Not initialized", tip = "Wait for DataStore to load"},
        {pattern = "invalid order", hint = "Order error", tip = "Check order direction"},
        {pattern = "invalid filter", hint = "Filter error", tip = "Check filter format"},
        {pattern = "path not found", hint = "No path", tip = "Goal may be unreachable"},
        {pattern = "invalid waypoint", hint = "Bad waypoint", tip = "Waypoint may be invalid"},
        {pattern = "path blocked", hint = "Path blocked", tip = "Obstacles in path"},
        {pattern = "invalid mass", hint = "Mass error", tip = "Check part mass properties"},
        {pattern = "cannot align", hint = "Alignment failed", tip = "Check constraints"},
        {pattern = "joint error", hint = "Joint failed", tip = "Check attachment points"},
        {pattern = "invalid anchor point", hint = "Bad anchor", tip = "Anchor point must be 0-1"},
        {pattern = "invalid position", hint = "Bad position", tip = "Check UDim2 format"},
        {pattern = "invalid size", hint = "Bad size", tip = "Check UDim2 format"},
        {pattern = "text too long", hint = "Text overflow", tip = "Text exceeds bounds"},
        {pattern = "font not found", hint = "Missing font", tip = "Font may not be available"},
        {pattern = "invalid keycode", hint = "Bad KeyCode", tip = "Check Enum.KeyCode value"},
        {pattern = "invalid userinput", hint = "Bad InputType", tip = "Check Enum.UserInputType"},
        {pattern = "context action not found", hint = "Missing action", tip = "Action not bound"},
        {pattern = "sound not loaded", hint = "Sound not ready", tip = "Wait for sound to load"},
        {pattern = "invalid sound id", hint = "Bad sound ID", tip = "Check sound asset ID"},
        {pattern = "playback failed", hint = "Play error", tip = "Sound may be corrupted"},
        {pattern = "invalid track", hint = "Bad animation", tip = "Animation may not be loaded"},
        {pattern = "cannot play animation", hint = "Play failed", tip = "Check humanoid and animator"},
        {pattern = "invalid asset", hint = "Bad asset ID", tip = "Check if asset exists"},
        {pattern = "purchase failed", hint = "Buy error", tip = "Check currency and permissions"},
        {pattern = "cannot send message", hint = "Chat blocked", tip = "Rate limit or banned"},
        {pattern = "message too long", hint = "Chat limit", tip = "Message exceeds character limit"},
        {pattern = "teleport failed", hint = "Teleport error", tip = "Check place ID and permissions"},
        {pattern = "invalid teleport data", hint = "Bad teleport data", tip = "Data must be JSON serializable"},
        {pattern = "voice not enabled", hint = "Voice off", tip = "Enable voice in settings"},
        {pattern = "cannot connect to voice", hint = "Voice connect failed", tip = "Check microphone permissions"},
    }
}